/*
 * This file was automatically generated by EvoSuite
 * Sun Jan 04 09:18:34 GMT 2026
 */

package com.mycompany.app;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.mycompany.app.Book;
import com.mycompany.app.LoanService;
import java.time.LocalDate;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.time.MockLocalDate;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class LoanService_ESTest extends LoanService_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      LoanService loanService0 = new LoanService(1310);
      LocalDate localDate0 = MockLocalDate.ofEpochDay(1310);
      Book book0 = new Book("q`/!n20]1", "q`/!n20]1", "q`/!n20]1", localDate0, 1310);
      loanService0.borrow(book0, "q`/!n20]1");
      boolean boolean0 = loanService0.isOverdue(book0, "q`/!n20]1", localDate0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      LoanService loanService0 = null;
      try {
        loanService0 = new LoanService((-1744));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // defaultLoanDays must be > 0
         //
         verifyException("com.mycompany.app.LoanService", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      LoanService loanService0 = new LoanService(1328);
      LocalDate localDate0 = MockLocalDate.now();
      // Undeclared exception!
      try { 
        loanService0.isOverdue((Book) null, "4rADZzDxhLxzi8hr", localDate0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.mycompany.app.LoanService", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      LoanService loanService0 = new LoanService(1310);
      LocalDate localDate0 = MockLocalDate.ofEpochDay(1310);
      Book book0 = new Book("q`/!n20]1", "q`/!n20]1", "q`/!n20]1", localDate0, 1310);
      boolean boolean0 = loanService0.isOverdue(book0, "w9nOr8s3f8qI+8", localDate0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      LoanService loanService0 = new LoanService(445);
      Book book0 = new Book("_SgBRx+UktGvd0@Hd:L", "", "", (LocalDate) null, 445);
      // Undeclared exception!
      try { 
        loanService0.borrow(book0, "");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // book and userId are required
         //
         verifyException("com.mycompany.app.LoanService", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      LoanService loanService0 = new LoanService(1310);
      LocalDate localDate0 = MockLocalDate.ofEpochDay(1310);
      Book book0 = new Book("q`/!n20]1", "q`/!n20]1", "q`/!n20]1", localDate0, 1310);
      // Undeclared exception!
      try { 
        loanService0.borrow(book0, (String) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // book and userId are required
         //
         verifyException("com.mycompany.app.LoanService", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      LoanService loanService0 = new LoanService(1);
      LocalDate localDate0 = MockLocalDate.ofYearDay(1, 1);
      Book book0 = new Book("book and userId are required", "book and userId are required", "book and userId are required", localDate0, 0);
      // Undeclared exception!
      try { 
        loanService0.borrow(book0, "book and userId are required");
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Book not available
         //
         verifyException("com.mycompany.app.LoanService", e);
      }
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      LoanService loanService0 = null;
      try {
        loanService0 = new LoanService(0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // defaultLoanDays must be > 0
         //
         verifyException("com.mycompany.app.LoanService", e);
      }
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      LoanService loanService0 = new LoanService(313);
      // Undeclared exception!
      try { 
        loanService0.borrow((Book) null, "Yq0XvNLY|#}:dWU#v$H");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // book and userId are required
         //
         verifyException("com.mycompany.app.LoanService", e);
      }
  }
}
