/*
 * This file was automatically generated by EvoSuite
 * Sun Jan 04 09:18:42 GMT 2026
 */

package com.mycompany.app;

import org.junit.Test;
import static org.junit.Assert.*;
import com.mycompany.app.App;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class App_ESTest extends App_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      App app0 = new App();
      int int0 = app0.add(1099, 2197);
      assertEquals(3296, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      App app0 = new App();
      int int0 = app0.add(0, 0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      App app0 = new App();
      int int0 = app0.add((-27), (-1492));
      assertEquals((-1492), int0);
  }
}
