/*
 * This file was automatically generated by EvoSuite
 * Sun Jan 04 09:19:53 GMT 2026
 */

package com.mycompany.app;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.mycompany.app.Book;
import java.time.LocalDate;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.time.MockLocalDate;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Book_ESTest extends Book_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.now();
      Book book0 = new Book("ISBN is required", "No copies available", "", localDate0, 1099);
      book0.borrow();
      assertEquals(1098, book0.getAvailableCopies());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Book book0 = new Book("Available copies cannot be negative", "Available copies cannot be negative", "Available copies cannot be negative", (LocalDate) null, 634);
      int int0 = book0.getAvailableCopies();
      assertEquals(634, int0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.now();
      Book book0 = new Book("Q1", "Q1", "Q1", localDate0, 592);
      boolean boolean0 = book0.canBorrow();
      assertEquals(592, book0.getAvailableCopies());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Book book0 = new Book("ISBN is required", "ISBN is required", "ISBN is required", (LocalDate) null, 1099);
      Book book1 = new Book("ISBN is required", "ISBN is required", "ISBN is required", (LocalDate) null, 1099);
      book0.equals(book1);
      assertEquals(1099, book1.getAvailableCopies());
      assertEquals(1099, book0.getAvailableCopies());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Book book0 = new Book("Available copies cannot be negative", "Available copies cannot be negative", "2;=*/]:r>7Vt|#j", (LocalDate) null, 0);
      boolean boolean0 = book0.equals(book0);
      assertEquals("Available copies cannot be negative", book0.getIsbn());
      assertFalse(book0.canBorrow());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Book book0 = new Book("Available copies cannot be negative", "Available copies cannot be negative", "2;=*/]:r>7Vt|#j", (LocalDate) null, 0);
      Object object0 = new Object();
      boolean boolean0 = book0.equals(object0);
      assertFalse(boolean0);
      assertEquals("Available copies cannot be negative", book0.getIsbn());
      assertFalse(book0.canBorrow());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Book book0 = new Book("Available copies cannot be negative", "Available copies cannot be negative", "2;=*/]:r>7Vt|#j", (LocalDate) null, 0);
      // Undeclared exception!
      try { 
        book0.borrow();
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // No copies available
         //
         verifyException("com.mycompany.app.Book", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Book book0 = new Book("Available copies cannot be negative", "Available copies cannot be negative", "2;=*/]:r>7Vt|#j", (LocalDate) null, 0);
      boolean boolean0 = book0.canBorrow();
      assertFalse(boolean0);
      assertEquals("Available copies cannot be negative", book0.getIsbn());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Book book0 = null;
      try {
        book0 = new Book("Available copies cannot be negative", "Available copies cannot be negative", "Available copies cannot be negative", (LocalDate) null, (-2750));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Available copies cannot be negative
         //
         verifyException("com.mycompany.app.Book", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Book book0 = null;
      try {
        book0 = new Book("", "", "H{S0O>EJ)w}yt4Nr4", (LocalDate) null, 0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // ISBN is required
         //
         verifyException("com.mycompany.app.Book", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Book book0 = null;
      try {
        book0 = new Book((String) null, (String) null, (String) null, (LocalDate) null, 139);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // ISBN is required
         //
         verifyException("com.mycompany.app.Book", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Book book0 = new Book("Available copies cannot be negative", "Available copies cannot be negative", "2;=*/]:r>7Vt|#j", (LocalDate) null, 0);
      String string0 = book0.getIsbn();
      assertEquals("Available copies cannot be negative", string0);
      assertEquals(0, book0.getAvailableCopies());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Book book0 = new Book("Available copies cannot be negative", "Available copies cannot be negative", "2;=*/]:r>7Vt|#j", (LocalDate) null, 0);
      book0.hashCode();
      assertFalse(book0.canBorrow());
      assertEquals("Available copies cannot be negative", book0.getIsbn());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Book book0 = new Book("Available copies cannot be negative", "Available copies cannot be negative", "2;=*/]:r>7Vt|#j", (LocalDate) null, 0);
      int int0 = book0.getAvailableCopies();
      assertEquals(0, int0);
      assertEquals("Available copies cannot be negative", book0.getIsbn());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Book book0 = new Book("Available copies cannot be negative", "Available copies cannot be negative", "2;=*/]:r>7Vt|#j", (LocalDate) null, 0);
      book0.returnBook();
      assertEquals(1, book0.getAvailableCopies());
      
      book0.borrow();
      assertFalse(book0.canBorrow());
  }
}
